
spring:
  datasource:
    url: jdbc:postgresql://31.40.251.201:5432/javapro?user=javapro&password=iddqd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    url: jdbc:postgresql://31.40.251.201:5432/javapro
    user: javapro
    password: iddqd
    enabled: true
  mail:
    address: http://localhost:8080
    host: smtp.gmail.com
    port: 587
    username: devSocialLine@gmail.com
    password: ntcngjxnf12
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
server:
  port: 8085



